from django.conf.urls import url

from bookings.views import *
from . import views

urlpatterns = [
    url(r'^$', views.web, name='index_public'),
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^feedback/$', views.contact, name='contact'),

    url(r'^frontend/slider/index/$', views.SliderListView.as_view(), name='slider_list'),
    url(r'^frontend/slider/add/$', views.SliderCreateView.as_view(), name='slider_create'),
    url(r'^frontend/slider/update/(?P<slider_pk>\d+)/$', views.SliderUpdateView.as_view(), name='slider_update'),
    url(r'^frontend/slider/view/(?P<slider_pk>\d+)/$', views.slider_view, name='slider_view'),
    url(r'^frontend/slider/delete/(?P<slider_pk>\d+)/$', views.slider_delete, name='slider_delete'),

    url(r'^frontend/about/index/$', views.AboutListView.as_view(), name='about_list'),
    url(r'^frontend/about/add/$', views.AboutCreateView.as_view(), name='about_create'),
    url(r'^frontend/about/update/(?P<about_pk>\d+)/$', views.AboutUpdateView.as_view(), name='about_update'),
    url(r'^frontend/about/view/(?P<about_pk>\d+)/$', views.about_view, name='about_view'),
    url(r'^frontend/about/details/(?P<about_pk>\d+)/$', views.about_detail, name='about_detail'),
    url(r'^frontend/about/delete/(?P<about_pk>\d+)/$', views.about_delete, name='about_delete'),

    url(r'^announcement/news/index/$', views.NewsListView.as_view(), name='news_list'),
    url(r'^announcement/news/$', views.news_wall, name='news_wall'),
    url(r'^announcement/news/add/$', views.NewsCreateView.as_view(), name='news_create'),
    url(r'^announcement/news/update/(?P<news_pk>\d+)/$', views.NewsUpdateView.as_view(), name='news_update'),
    url(r'^announcement/news/view/(?P<news_pk>\d+)/$', views.news_view, name='news_view'),
    url(r'^announcement/news/details/(?P<news_pk>\d+)/$', views.news_detail, name='news_detail'),
    url(r'^announcement/news/delete/(?P<news_pk>\d+)/$', views.news_delete, name='news_delete'),

    url(r'^trip/index/$', views.EventListView.as_view(), name='event_list'),
    url(r'^trip/$', views.event_wall, name='event_wall'),
    url(r'^trip/add/$', views.EventCreateView.as_view(), name='event_create'),
    url(r'^trip/edit/(?P<event_pk>\d+)/$', views.EventUpdateView.as_view(), name='event_update'),
    url(r'^trip/view/(?P<event_pk>\d+)/$', views.event_view, name='event_view'),
    url(r'^trip/details/(?P<event_pk>\d+)/$', views.event_detail, name='event_detail'),
    url(r'^trip/delete(?P<event_pk>\d+)/$', views.event_delete, name='event_delete'),
    url(r'^trip/(?P<trip_pk>[0-9]+)/$', views.book_trip, name='book_trip'),
    url(r'^trip/booking/new/(?P<trip_pk>[0-9]+)/', views.reserve_trip_slot, name='reserve_trip_slot'),
    url(r'^trip/bookings/$', views.user_trip_bookings, name='user_trip_bookings'),
    url(r'^trip/bookings/cancel/(?P<trip_pk>[0-9]+)$', views.cancel_trip_booking, name='cancel_trip_booking'),
    url(r'^trip/bookings/pdf/(?P<trip_pk>[0-9]+)/$', GenerateTripPDF.as_view(), name='generate_trip_pdf'),

    url(r'^(?P<id>[0-9]+)/reviews/create$', views.EventReviewCreateView.as_view(), name='createreview'),
    url(r'^(?P<pk>[0-9]+)/reviews/edit$', views.EventReviewUpdateView.as_view(), name='editreview'),
    url(r'^(?P<pk>[0-9]+)/reviews/delete$', views.EventReviewDeleteView.as_view(), name='deletereview'),

    url(r'^accommodation/index/$', views.AccommodationListView.as_view(), name='accommodation_list'),
    url(r'^accommodation/search/$', views.accommodation_search.as_view(), name='accommodation_search'),
    url(r'^accommodation/add/$', views.AccommodationCreateView.as_view(), name='accommodation_create'),
    url(r'^accommodation/edit/(?P<accommodation_pk>\d+)/$', views.AccommodationUpdateView.as_view(), name='accommodation_update'),
    url(r'^accommodation/view/(?P<accommodation_pk>\d+)/$', views.accommodation_view, name='accommodation_view'),
    url(r'^accommodation/details/(?P<accommodation_pk>\d+)/$', views.accommodation_detail, name='accommodation_detail'),
    url(r'^accommodation/delete(?P<accommodation_pk>\d+)/$', views.accommodation_delete, name='accommodation_delete'),
    url(r'^accommodation/(?P<accommodation_pk>[0-9]+)/room/(?P<room_pk>[0-9]+)$', views.book_room, name='book_room'),
    url(r"^accommodation/booking/new/(?P<room_pk>[0-9]+)/(?P<accommodation_pk>[0-9]+)/(?P<checkin>(\d{4}-\d{2}-\d{2}))/(?P<checkout>(\d{4}-\d{2}-\d{2}))/(?P<totalcost>[0-9]+)$", views.reserve_room, name='reserve_room'),
    url(r'^accommodation/bookings/$', views.user_bookings, name='user_bookings'),
    url(r'^accommodation/bookings/cancel/(?P<booking_pk>[0-9]+)$', views.cancel_booking, name='cancel_booking'),
    url(r'^accommodation/bookings/pdf/(?P<booking_pk>[0-9]+)/$', GeneratePDF.as_view(), name='generate_pdf'),

    url(r'^(?P<id>[0-9]+)/reviews/create$', views.AccommodationReviewCreateView.as_view(), name='createreview'),
    url(r'^(?P<pk>[0-9]+)/reviews/edit$', views.AccommodationReviewUpdateView.as_view(), name='editreview'),
    url(r'^(?P<pk>[0-9]+)/reviews/delete$', views.AccommodationReviewDeleteView.as_view(), name='deletereview'),

    url(r'^room/index/$', views.RoomListView.as_view(), name='room_list'),
    url(r'^room/add/$', views.room_create, name='room_create'),
    url(r'^room/edit/(?P<room_pk>\d+)/$', views.RoomUpdateView.as_view(), name='room_update'),
    url(r'^room/view/(?P<room_pk>\d+)/$', views.room_view, name='room_view'),
    url(r'^room/delete/(?P<room_pk>\d+)/$', views.room_delete, name='room_delete'),

    url(r'^room/type/index/$', views.TypeListView.as_view(), name='type_list'),
    url(r'^room/type/add/$', views.TypeCreateView.as_view(), name='type_create'),
    url(r'^room/type/edit/(?P<type_pk>\d+)/$', views.TypeUpdateView.as_view(), name='type_update'),
    url(r'^room/type/view/(?P<type_pk>\d+)/$', views.type_view, name='type_view'),
    url(r'^room/type/delete/(?P<type_pk>\d+)/$', views.type_delete, name='type_delete'),

    url(r'^route/index/$', views.RouteListView.as_view(), name='route_list'),
    url(r'^route/search/$', views.route_search.as_view(), name='route_search'),
    url(r'^route/add/$', views.RouteCreateView.as_view(), name='route_create'),
    url(r'^route/edit/(?P<route_pk>\d+)/$', views.RouteUpdateView.as_view(), name='route_update'),
    url(r'^route/view/(?P<route_pk>\d+)/$', views.route_view, name='route_view'),
    url(r'^route/details/(?P<route_pk>\d+)/$', views.route_detail, name='route_detail'),
    url(r'^route/delete(?P<route_pk>\d+)/$', views.route_delete, name='route_delete'),
    url(r'^route/(?P<route_pk>[0-9]+)/bus/(?P<bus_pk>[0-9]+)$', views.book_bus, name='book_bus'),
    url(r"^route/booking/new/(?P<bus_pk>[0-9]+)/(?P<route_pk>[0-9]+)/", views.reserve_bus, name='reserve_bus'),
    url(r'^route/bookings/$', views.user_bus_bookings, name='user_bus_bookings'),
    url(r'^route/bookings/cancel/(?P<booking_pk>[0-9]+)$', views.cancel_bus_booking, name='cancel_bus_booking'),
    url(r'^route/bookings/pdf/(?P<booking_pk>[0-9]+)/$', GenerateBusPDF.as_view(), name='generate_bus_pdf'),

    url(r'^bus/index/$', views.BusListView.as_view(), name='bus_list'),
    url(r'^bus/add/$', views.BusCreateView.as_view(), name='bus_create'),
    url(r'^bus/edit/(?P<bus_pk>\d+)/$', views.BusUpdateView.as_view(), name='bus_update'),
    url(r'^bus/view/(?P<bus_pk>\d+)/$', views.bus_view, name='bus_view'),
    url(r'^bus/delete/(?P<bus_pk>\d+)/$', views.bus_delete, name='bus_delete'),

    url(r'^taxi/index/$', views.TaxiListView.as_view(), name='taxi_list'),
    url(r'^taxi/$', views.taxi_wall, name='taxi_wall'),
    url(r'^taxi/add/$', views.TaxiCreateView.as_view(), name='taxi_create'),
    url(r'^taxi/edit/(?P<taxi_pk>\d+)/$', views.TaxiUpdateView.as_view(), name='taxi_update'),
    url(r'^taxi/view/(?P<taxi_pk>\d+)/$', views.taxi_view, name='taxi_view'),
    url(r'^taxi/delete(?P<taxi_pk>\d+)/$', views.taxi_delete, name='taxi_delete'),
    url(r'^taxi/(?P<taxi_pk>[0-9]+)/$', views.book_taxi, name='book_taxi'),
    url(r'^taxi/booking/new/(?P<taxi_pk>[0-9]+)/', views.reserve_taxi_slot, name='reserve_taxi_slot'),
    url(r'^taxi/bookings/$', views.user_taxi_bookings, name='user_taxi_bookings'),
    url(r'^taxi/bookings/cancel/(?P<taxi_pk>[0-9]+)$', views.cancel_taxi_booking, name='cancel_taxi_booking'),
    url(r'^taxi/bookings/pdf/(?P<taxi_pk>[0-9]+)/$', GenerateTaxiPDF.as_view(), name='generate_taxi_pdf'),

    url(r'^(?P<id>[0-9]+)/reviews/create$', views.TaxiReviewCreateView.as_view(), name='createreview'),
    url(r'^(?P<pk>[0-9]+)/reviews/edit$', views.TaxiReviewUpdateView.as_view(), name='editreview'),
    url(r'^(?P<pk>[0-9]+)/reviews/delete$', views.TaxiReviewDeleteView.as_view(), name='deletereview'),

    url(r'^cab/index/$', views.CabListView.as_view(), name='cab_list'),
    url(r'^cab/$', views.cab_wall, name='cab_wall'),
    url(r'^cab/add/$', views.CabCreateView.as_view(), name='cab_create'),
    url(r'^cab/edit/(?P<cab_pk>\d+)/$', views.CabUpdateView.as_view(), name='cab_update'),
    url(r'^cab/view/(?P<cab_pk>\d+)/$', views.cab_view, name='cab_view'),
    url(r'^cab/delete(?P<cab_pk>\d+)/$', views.cab_delete, name='cab_delete'),
    url(r'^cab/(?P<cab_pk>[0-9]+)/$', views.book_cab, name='book_cab'),
    url(r'^cab/booking/new/(?P<cab_pk>[0-9]+)/', views.reserve_cab_slot, name='reserve_cab_slot'),
    url(r'^cab/bookings/$', views.user_cab_bookings, name='user_cab_bookings'),
    url(r'^cab/bookings/cancel/(?P<cab_pk>[0-9]+)$', views.cancel_cab_booking, name='cancel_cab_booking'),
    url(r'^cab/bookings/pdf/(?P<cab_pk>[0-9]+)/$', GenerateCabPDF.as_view(), name='generate_cab_pdf'),

    url(r'^(?P<id>[0-9]+)/reviews/create$', views.CabReviewCreateView.as_view(), name='createreview'),
    url(r'^(?P<pk>[0-9]+)/reviews/edit$', views.CabReviewUpdateView.as_view(), name='editreview'),
    url(r'^(?P<pk>[0-9]+)/reviews/delete$', views.CabReviewDeleteView.as_view(), name='deletereview'),

    url(r'^driver/index/$', views.DriverListView.as_view(), name='driver_list'),
    url(r'^driver/$', views.driver_wall, name='driver_wall'),
    url(r'^driver/add/$', views.DriverCreateView.as_view(), name='driver_create'),
    url(r'^driver/edit/(?P<driver_pk>\d+)/$', views.DriverUpdateView.as_view(), name='driver_update'),
    url(r'^driver/view/(?P<driver_pk>\d+)/$', views.driver_view, name='driver_view'),
    url(r'^driver/details/(?P<driver_pk>\d+)/$', views.driver_detail, name='driver_detail'),
    url(r'^driver/delete(?P<driver_pk>\d+)/$', views.driver_delete, name='driver_delete'),

    url(r'^bookings/rooms/index/$', views.AccommodationBookingListView.as_view(), name='room_bookings_list'),
    url(r'^bookings/buses/index/$', views.BusBookingListView.as_view(), name='bus_bookings_list'),
    url(r'^bookings/trips/index/$', views.TripBookingListView.as_view(), name='trip_bookings_list'),
    url(r'^bookings/cabs/index/$', views.CabBookingListView.as_view(), name='cab_bookings_list'),
    url(r'^bookings/taxis/index/$', views.TaxiBookingListView.as_view(), name='taxi_bookings_list'),
]
