# Generated by Django 2.1.5 on 2020-03-12 19:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_image', models.ImageField(null=True, upload_to='about/', verbose_name='About Image')),
                ('about', models.TextField(max_length=500, verbose_name='About School')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
                'default_permissions': ('view', 'add', 'change', 'delete'),
            },
        ),
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Image')),
                ('lowest_charge', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('note', models.CharField(blank=True, max_length=300, null=True)),
                ('Is_View_on_Web', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=20, null=True, verbose_name='Is View On Web?')),
            ],
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AccommodationReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField(default=0)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Accommodation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Hotel Reviews',
            },
        ),
        migrations.CreateModel(
            name='AirportTaxi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=40)),
                ('ac', models.BooleanField(default=False)),
                ('total_seats', models.IntegerField(default='4')),
                ('taxi_type', models.CharField(choices=[('SUV', 'SUV'), ('TRUCK', 'Truck'), ('SEDAN', 'Sedan'), ('VAN', 'Van'), ('WAGON', 'Wagon'), ('CONVERTIBLE', 'Convertible'), ('SPORTS', 'Sports'), ('DIESEL', 'Diesel'), ('LUXURY', 'Luxury'), ('HATCHBACK', 'Hatchback'), ('OTHER', 'Other')], max_length=20)),
                ('taxi_info', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(null=True, upload_to='taxi')),
                ('fare_ratio', models.IntegerField(default=10)),
                ('source', models.CharField(max_length=40)),
                ('Is_View_on_Web', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=20, null=True, verbose_name='Is View On Web?')),
            ],
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AirportTaxiBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traveller_first_name', models.CharField(max_length=255)),
                ('traveller_last_name', models.CharField(max_length=255)),
                ('travel_date', models.DateField()),
                ('destination', models.CharField(max_length=40)),
                ('travel_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.AirportTaxi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Airport Taxi Reservations',
            },
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=40)),
                ('ac', models.BooleanField(default=False)),
                ('total_seats', models.IntegerField(default='56')),
                ('departure_time', models.TimeField()),
                ('image', models.ImageField(null=True, upload_to='bus')),
                ('Is_View_on_Web', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=20, null=True, verbose_name='Is View On Web?')),
            ],
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='BusReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traveller_first_name', models.CharField(max_length=255)),
                ('traveller_last_name', models.CharField(max_length=255)),
                ('travel_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Bus')),
            ],
            options={
                'verbose_name_plural': 'Bus Reservations',
            },
        ),
        migrations.CreateModel(
            name='BusReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField(default=0)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Bus')),
            ],
            options={
                'verbose_name_plural': 'Bus Reviews',
            },
        ),
        migrations.CreateModel(
            name='CabReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField(default=0)),
                ('cab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.AirportTaxi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Hotel Review',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=16)),
                ('address', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(null=True, upload_to='profile')),
                ('rating', models.CharField(blank=True, max_length=100, null=True)),
                ('Is_View_on_Web', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=20, null=True, verbose_name='Is View On Web?')),
            ],
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=100, verbose_name='Trip Title')),
                ('event_for', models.CharField(choices=[('All', 'All'), ('Family', 'Family'), ('Singles', 'Singles'), ('Couples', 'Couples'), ('Children', 'Children')], max_length=100, verbose_name='Trip For')),
                ('event_place', models.CharField(max_length=100, verbose_name='Trip Place')),
                ('from_date', models.DateField(verbose_name='From Date')),
                ('to_date', models.DateField(verbose_name='To Date')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Image')),
                ('price', models.PositiveIntegerField()),
                ('offer', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('Is_View_on_Web', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=20, null=True, verbose_name='Is View On Web?')),
            ],
            options={
                'ordering': ('from_date',),
                'default_permissions': ('view', 'add', 'change', 'delete'),
            },
        ),
        migrations.CreateModel(
            name='EventReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Trip Review',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the sender', max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Feedback',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=100, verbose_name='News Title')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('image', models.ImageField(null=True, upload_to='images/', verbose_name='Image')),
                ('news', models.TextField(blank=True, verbose_name='News')),
                ('Is_View_on_Web', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=20, verbose_name='Is View On Web?')),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'ordering': ('-date',),
                'default_permissions': ('view', 'add', 'change', 'delete'),
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_first_name', models.CharField(max_length=255)),
                ('guest_last_name', models.CharField(max_length=255)),
                ('CheckIn', models.DateField()),
                ('CheckOut', models.DateField()),
                ('totalPrice', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Accommodation')),
            ],
            options={
                'verbose_name_plural': 'Reservation',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalRooms', models.CharField(max_length=255)),
                ('View', models.BooleanField(default=True)),
                ('capacity', models.IntegerField(default=1)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Accommodation', verbose_name='Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=None, validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.CharField(default=None, max_length=200)),
                ('airConditioning', models.BooleanField(default=False, verbose_name='Air Conditioning')),
                ('wifi', models.BooleanField(default=False, verbose_name='WiFi')),
                ('roomService', models.BooleanField(default=False, verbose_name='Room Service')),
                ('freeBreakfast', models.BooleanField(default=False, verbose_name='Free Breakfast')),
                ('minibar', models.BooleanField(default=False, verbose_name='Mini Bar')),
                ('laundaryService', models.BooleanField(default=False, verbose_name='Laundary Service')),
                ('poolFacility', models.BooleanField(default=False, verbose_name='Pool Facility')),
                ('image', models.ImageField(blank=True, null=True, upload_to='RoomTypes/', verbose_name='Room Type Image')),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Accommodation', verbose_name='Hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_point', models.CharField(max_length=300)),
                ('via', models.CharField(max_length=300)),
                ('end_point', models.CharField(max_length=300)),
                ('route_time', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.PositiveIntegerField(default=None, validators=[django.core.validators.MinValueValidator(1)])),
                ('Is_View_on_Web', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=20, null=True, verbose_name='Is View On Web?')),
            ],
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_image', models.ImageField(upload_to='sliders/', verbose_name='Slider Image')),
                ('image_title', models.CharField(max_length=100, verbose_name='Image Title')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
            ],
            options={
                'default_permissions': ('view', 'add', 'change', 'delete'),
            },
        ),
        migrations.CreateModel(
            name='Taxi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=40)),
                ('ac', models.BooleanField(default=False)),
                ('total_seats', models.IntegerField(default='4')),
                ('taxi_type', models.CharField(choices=[('SUV', 'SUV'), ('TRUCK', 'Truck'), ('SEDAN', 'Sedan'), ('VAN', 'Van'), ('WAGON', 'Wagon'), ('CONVERTIBLE', 'Convertible'), ('SPORTS', 'Sports'), ('DIESEL', 'Diesel'), ('LUXURY', 'Luxury'), ('HATCHBACK', 'Hatchback'), ('OTHER', 'Other')], max_length=20)),
                ('taxi_info', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(null=True, upload_to='taxi')),
                ('fare_ratio', models.IntegerField(default=10)),
                ('source', models.CharField(max_length=40)),
                ('Is_View_on_Web', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=20, null=True, verbose_name='Is View On Web?')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Driver')),
            ],
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TaxiBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traveller_first_name', models.CharField(max_length=255)),
                ('traveller_last_name', models.CharField(max_length=255)),
                ('travel_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('travel_time', models.TimeField()),
                ('taxi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Taxi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Special Hire Reservations',
            },
        ),
        migrations.CreateModel(
            name='TaxiReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField(default=0)),
                ('taxi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Taxi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Hotel Review',
            },
        ),
        migrations.CreateModel(
            name='TripBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tourist_first_name', models.CharField(max_length=255)),
                ('tourist_last_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Trip',
            },
        ),
        migrations.AddField(
            model_name='room',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.RoomType', verbose_name='Room Type'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Room'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='busreview',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Route'),
        ),
        migrations.AddField(
            model_name='busreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='busreservation',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Route'),
        ),
        migrations.AddField(
            model_name='busreservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bus',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Route'),
        ),
        migrations.AddField(
            model_name='airporttaxi',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Driver'),
        ),
    ]
